#!/bin/bash

# Validation
# Check if ran with root privileges
if [[ $EUID > 0 ]]; then # we can compare directly with this syntax.
  echo "You must run script with root privileges!"
  exit 1
fi

# Check for supplied action
if [[ $1 != 'create' ]] && [[ $1 != 'delete' ]]; then
    echo 'You must choose operation! Either create or delete...'
    exit 1;
fi

# Check for supplied vhost name
if [[ $2 = '' ]]; then
    echo 'You must enter vhost name!'
    exit 1;
fi

if [[ $1 = 'create' ]]; then
    echo "<VirtualHost *:80>
    ServerAdmin admin@$2.local
    ServerName $2.local
    ServerAlias www.$2.local
    DocumentRoot /var/www/html/$2
    ErrorLog /var/log/apache2/$2-error.log
    CustomLog /var/log/apache2/$2-access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$2.local.conf
    echo -e "127.0.0.1\t$2.local www.$2.local" >> /etc/hosts

    chown -R www-data:www-data /var/www/html/$2
    chmod -R 775 /var/www/html/$2

    a2ensite -q $2.local.conf > /dev/null

    apache2ctl graceful

    echo "$2.local vhost created."

    exit 0
fi

if [[ $1 = 'delete' ]]; then
    a2dissite $2.local.conf > /dev/null

    sed "/$2\.local/d" -i /etc/hosts

    rm /etc/apache2/sites-available/$2.local.conf

    apache2ctl graceful

    echo "$2.local vhost deleted."

    exit 0
fi
